### PR TITLE
PC-1465: Updated test

### PR DESCRIPTION
**Pull request by Glenn-Clarke**
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1465)

### CODE REVIEW

**Comment by Glenn-Clarke** [comment]
@jdgage Is this in line with what you had in mind, to sharpen the test a bit?

**Comment by jdgage** [comment]
Yes this is what I was imagining - could you change "old EPC" to "multiple EPCs" across the board though? Risk of it being misunderstood as a single 'old' EPC as is I think.

**Comment by Glenn-Clarke** [comment]
True, I'll edit it!

**Review by samyou-softwire — APPROVED** [review]
is this ready to go?

**Review by jdgage — APPROVED** [review]

**Pull request merged**
