### PR TITLE
PC-1375: Remove text length limits from Scottish EPC text

### PR DESCRIPTION
**Pull request by samyou-softwire**
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1375)

# Description

we decided that the text lengths for some potentially variable length EPC fields weren't worth it, so they are removed in this PR

made them django TextFields to allow for this/ the documentation says that a CharField can have unlimited length but in practice django would not allow it

# Checklist

- [x] I have made any necessary updates to the documentation
- [x] I have checked there are no unnecessary IDE warnings in this PR
- [x] I have checked there are no unintentional line ending changes
- [x] I have added tests where applicable
- [x] If I have made any changes to the code, I have used the IDE auto-formatter on it
- [x] If I have made any changes to Python files (even if not changing any content strings), I have run `make extract-translations`

### CODE REVIEW

**Review by jdgage — COMMENTED** [review]
I think for obvious cases, e.g. postcode, EPC rating(?) we should still have max length

**Comment by samyou-softwire** [comment]
> I think for obvious cases, e.g. postcode, EPC rating(?) we should still have max length

I suppose without further research into the data I'd be wary, we have little control over the data format. e.g. for EPC rating I'm fairly certain an observed option is 'None' or wtte. we could overestimate those but it feels like it defeats the point

**Comment by jdgage** [comment]
I'd be fine with having things be either 'short text' i.e. 20 char limit or 'long text' i.e. no limit. I think we do need to be mindful of how much disk space this table is going to take up.

**Comment by samyou-softwire** [comment]
> I'd be fine with having things be either 'short text' i.e. 20 char limit or 'long text' i.e. no limit. I think we do need to be mindful of how much disk space this table is going to take up.

have pared back the changes a bit now to mostly text fields

**Review by jdgage — APPROVED** [review]

**Pull request merged**
